site_name: Prison Reform Trust Cookiecutter Data Science
site_description: A project template and directory structure for Prison Reform Trust Python data projects.
repo_url: https://github.com/alexhewson/prt-cookiecutter-data-science
edit_uri: edit/master/docs/
copyright: Written by Prison Reform Trust. This project is heavily indebted to <a target=_blanks href="https://www.drivendata.org">DrivenData</a> and <a target=_blanks href="https://github.com/hackalog/easydata">EasyData</a>.
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  features:
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - content.code.copy
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
        
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: prison-reform-trust
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode
    
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference
  icon:
    admonition:
      tip: material/tooltip-check-outline
extra_css:
  - css/extra.css
nav:
  - Welcome: index.md
  - Setting up a development environment: setting-up-a-development-environment.md
  - Starting a new project: starting-a-new-project.md
  - Updating your environment: updating-your-environment.md
  - Opinions: opinions.md
