site_name: Prison Reform Trust Cookiecutter Data Science
site_description: A project template and directory structure for Prison Reform Trust Python data projects.
site_favicon: favicon.ico
repo_url: https://github.com/Prison-Reform-Trust/prt-cookiecutter-data-science
edit_uri: edit/master/docs/docs
copyright: Prison Reform Trust, with this project heavily indebted to the friendly folks at <a target=_blanks href="https://www.drivendata.org">DrivenData</a>.
theme: cinder
extra_css:
  - css/extra.css
nav:
  - Home: index.md
